In [2]:
%pylab inline

from __future__ import print_function
from __future__ import division

import sklearn
import numpy
import scipy
import pandas
import matplotlib
import seaborn

import json
import re

from matplotlib import pyplot
from collections import Counter

from sklearn.feature_extraction.text import CountVectorizer

Populating the interactive namespace from numpy and matplotlib


In [3]:
def getlinesep(mail):
    lineseps = ['\r\n', '\n']
    return next(x for x in lineseps if 2 * x in mail)

def parse(mail):
    ls = getlinesep(mail)
    bs = 2 * ls
    
    header, body = mail.split(bs, 1)
    header = header.replace(ls + '\t', ' ').replace(ls + ' ', ' ')
    
    header = [(str(x).replace('_', '--'), y) for x, y in [z.split(':', 1) for z in header.split(ls)]]
    body = ('body', body)
    
    return header + [body] + [('my_linesep', ls)]

def try_parse(mail):
    try:
        return parse(mail)
    except ValueError:
        return {'my_unparseable': True, 'my_reason': 'badheader'}
    except StopIteration:
        return {'my_unparseable': True, 'my_reason': 'nosep'}
    


In [33]:
vectorizer = CountVectorizer(min_df=1)
corpus = [
     'This is the first document.',
     'This is the second second document.',
     'And the third one.',
     'Is this the first document?',
]
X = vectorizer.fit_transform(corpus)
analyze = vectorizer.build_analyzer()
analyze("This is a text document to analyze.") 
last1 = vectorizer.get_feature_names()
last2 = X.toarray()
print(last1)
print(last2)

[u'and', u'document', u'first', u'is', u'one', u'second', u'the', u'third', u'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [117]:
data = pandas.read_csv('data/train.csv', usecols = ['body', 'spam']).fillna('')

# Count Vectorizer

In [149]:
data.index.size

81000

In [215]:
vec = CountVectorizer(token_pattern = r'[a-z]{4,}', min_df = 800)
counts = vec.fit_transform(data.body)

In [216]:
appareances = counts.minimum(1)

In [217]:
Pw = appareances.mean(axis = 0)

In [218]:
Pws = appareances[numpy.where(data.spam)].mean(axis = 0)

In [219]:
Ps = data.spam.mean()

In [220]:
Psw = Pws * Ps / Pw

In [221]:
counts.shape

(81000, 1649)

In [172]:
Psw.todd

matrix([[ 0.35151515,  0.54545455,  0.3859098 , ...,  0.817083  ,
          0.82244254,  0.54085155]])

array([ 0.35151515,  0.54545455,  0.3859098 , ...,  0.817083  ,
        0.82244254,  0.54085155])

(10, 671)

array([ 361,  324,  420, 1246,  942,  437,  359,  243,  443,  693])

In [176]:
a = vec.get_feature_names()

In [178]:
type(a)

list

In [212]:
numpy.sort(Psw)

matrix([[ 0.,  0.,  0., ...,  1.,  1.,  1.]])

In [210]:
numpy.array(vec.get_feature_names())[[numpy.argsort(numpy.asarray(Psw)[0])[::-1][:10]]]

array([u'dcenter', u'corel', u'dleft', u'rfkindysadvnqw', u'nerasdf',
       u'dreamweaver', u'dbaseline', u'cialis', u'dwindows', u'imageready'], 
      dtype='<U15')

In [156]:
]vec.get_feature_names()[numpy.argmax(Psw)]

u'cialis'

In [148]:
map(print, data[data.body.str.contains('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaamwaazgaamqaazaaa')].body)

this is a multi-part message in mime format.<CR><NL><CR><NL>------=_nextpart_000_2cf2_01c5b2fd.4f6ed220<CR><NL>content-type: text/html;<CR><NL>	charset="iso-8859-7"<CR><NL>content-transfer-encoding: quoted-printable<CR><NL><CR><NL><!doctype html public "-//w3c//dtd html 4.0 transitional//en"><CR><NL><html><head><CR><NL><meta http-equiv=3dcontent-type content=3d"text/html; =<CR><NL>charset=3diso-8859-1"><CR><NL><meta content=3d"mshtml 6.00.2900.2523" name=3dgenerator><CR><NL><style></style><CR><NL></head><CR><NL><body bgcolor=3d#ffffff><CR><NL><div><font face=3darial size=3d2><a =<CR><NL>href=3d"http://uzrtcsdp.realrxonline.com/b/tzjbwja5mtfymgvnmfawba=3d=3d">=<CR><NL><img alt=3d""=20<CR><NL>hspace=3d0 src=3d"cid:422686c4d3c0$2180fea0$855aa5c0#####" =<CR><NL>align=3dbaseline=20<CR><NL>border=3d0></a></font></div><CR><NL><div><font face=3darial size=3d2></font>&nbsp;</div><CR><NL><div><!--startfragment -->&nbsp;<font =<CR><NL>color=3d#eaeaea>navymarrieddextrosecowardhandmaidenchester.jog

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [77]:
type(appareances)

scipy.sparse.csr.csr_matrix

In [84]:
data['spam'] = data.index > 50

In [89]:
q = appareances[data.spam]

In [86]:
appareances.shape

(100, 4108)

In [91]:
data.spam.sum()

49

In [93]:
data.spam.shape

(100,)

In [104]:
numpy.where(appareances)

(49, 4108)

In [109]:
numpy.asarray(appareances.todense())[data.spam == True].shape

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  if __name__ == '__main__':


(100, 4108)

In [ ]:
Pws = appareances[data.spam].mean(axis = 0)

In [110]:
data.spam

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...  
70     True
71     True
72     True
73     True
74     True
75     True
76     True
77     True
78     True
79     True
80     True
81     True
82     True
83     True
84     True
85     True
86     True
87     True
88     True
89     True
90     True
91     True
92     True
93     True
94     True
95     True
96     True
97     True
98     True
99     True
Name: spam, dtype: bool

In [112]:
numpy.where(data.spam)[0]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [115]:
appareances[numpy.where(data.spam)]

<49x4108 sparse matrix of type '<type 'numpy.int64'>'
	with 5504 stored elements in Compressed Sparse Row format>

In [66]:
appearences

<10x671 sparse matrix of type '<type 'numpy.int64'>'
	with 853 stored elements in Compressed Sparse Row format>

# Prueba

In [44]:
data = (pandas.read_csv('data/train.csv', usecols = ['body', 'spam']).fillna(''))

In [56]:
data = data[0:10]


SyntaxError: invalid syntax (<ipython-input-56-c4696dc27bb2>, line 2)

In [64]:
vec = CountVectorizer(token_pattern = r'[a-z]{4,}')
counts = vec.fit_transform(data.body)
appearences = counts.minimum(1)
Pw = appearences.mean(axis = 0)
Pws = appearences[data.spam].mean(axis = 0)
data.spam

#appearences.mean(axis=0)


0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: spam, dtype: bool

# Viejo

msg = data.body

In [73]:
def NL_to_spaces(s):
    return s.replace("<NL>", " ")

In [99]:
from sklearn.feature_extraction.text import CountVectorizer

def feature_names(s):
    vectorizer = CountVectorizer(min_df=1)
    #vectorizer.fit_transform(s)
    #return vectorizer.get_feature_names()
    print(s)
    return 4

map(feature_names, msg)

In [103]:
pepe = CountVectorizer(min_df = 5)

In [123]:
numpy.minimum(pepe.fit_transform(msg).todense(), 1).sum(axis = 0)

matrix([[ 5,  7,  5,  6,  5,  6,  5,  7,  6,  5,  6,  6,  9,  7,  5,  6, 10,
          6,  6,  7,  5,  5,  6,  8,  5,  7, 10,  5,  7]])

In [118]:
pepe.get_feature_names()

[u'an',
 u'and',
 u'are',
 u'be',
 u'but',
 u'can',
 u'day',
 u'for',
 u'from',
 u'have',
 u'if',
 u'in',
 u'is',
 u'it',
 u'know',
 u'me',
 u'nl',
 u'of',
 u'on',
 u'please',
 u'subject',
 u'thanks',
 u'that',
 u'the',
 u'they',
 u'this',
 u'to',
 u'we',
 u'you']

In [ ]:
º